# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.hooks import copy_metadata
import sys ; sys.setrecursionlimit(sys.getrecursionlimit() * 5)
datas = []
datas += collect_data_files('torch')
datas += collect_data_files('whisper')
datas += copy_metadata('tqdm')
datas += copy_metadata('regex')
datas += copy_metadata('sacremoses')
datas += copy_metadata('requests')
datas += copy_metadata('packaging')
datas += copy_metadata('filelock')
datas += copy_metadata('numpy')
datas += copy_metadata('tokenizers')
block_cipher = None


a = Analysis(
    ['main.py', 'ai.py'],
    pathex=[],
    binaries=[('/usr/local/bin/ffmpeg', '.'),
    ('/usr/local/opt/libarchive/lib/libarchive.13.dylib', '.'),
    ('/usr/local/lib/libFLAC++.10.dylib', '.'),
    ('/usr/local/lib/libFLAC++.dylib', '.'),
    ('/usr/local/lib/libFLAC.12.dylib', '.'),
    ('/usr/local/lib/libFLAC.dylib', '.'),
    ('/usr/local/lib/libIex-3_2.31.3.2.0.dylib', '.'),
    ('/usr/local/lib/libIex-3_2.31.dylib', '.'),
    ('/usr/local/lib/libIex-3_2.dylib', '.'),
    ('/usr/local/lib/libIex.dylib', '.'),
    ('/usr/local/lib/libIlmThread-3_2.31.3.2.0.dylib', '.'),
    ('/usr/local/lib/libIlmThread-3_2.31.dylib', '.'),
    ('/usr/local/lib/libIlmThread-3_2.dylib', '.'),
    ('/usr/local/lib/libIlmThread.dylib', '.'),
    ('/usr/local/lib/libImath-3_1.29.8.0.dylib', '.'),
    ('/usr/local/lib/libImath-3_1.29.dylib', '.'),
    ('/usr/local/lib/libImath-3_1.dylib', '.'),
    ('/usr/local/lib/libImath.dylib', '.'),
    ('/usr/local/lib/libOpenEXR-3_2.31.3.2.0.dylib', '.'),
    ('/usr/local/lib/libOpenEXR-3_2.31.dylib', '.'),
    ('/usr/local/lib/libOpenEXR-3_2.dylib', '.'),
    ('/usr/local/lib/libOpenEXR.dylib', '.'),
    ('/usr/local/lib/libOpenEXRCore-3_2.31.3.2.0.dylib', '.'),
    ('/usr/local/lib/libOpenEXRCore-3_2.31.dylib', '.'),
    ('/usr/local/lib/libOpenEXRCore-3_2.dylib', '.'),
    ('/usr/local/lib/libOpenEXRCore.dylib', '.'),
    ('/usr/local/lib/libOpenEXRUtil-3_2.31.3.2.0.dylib', '.'),
    ('/usr/local/lib/libOpenEXRUtil-3_2.31.dylib', '.'),
    ('/usr/local/lib/libOpenEXRUtil-3_2.dylib', '.'),
    ('/usr/local/lib/libOpenEXRUtil.dylib', '.'),
    ('/usr/local/lib/libSDL2-2.0.0.dylib', '.'),
    ('/usr/local/lib/libSDL2.dylib', '.'),
    ('/usr/local/lib/libSvtAv1Dec.0.8.7.dylib', '.'),
    ('/usr/local/lib/libSvtAv1Dec.0.dylib', '.'),
    ('/usr/local/lib/libSvtAv1Dec.dylib', '.'),
    ('/usr/local/lib/libSvtAv1Enc.1.7.0.dylib', '.'),
    ('/usr/local/lib/libSvtAv1Enc.1.dylib', '.'),
    ('/usr/local/lib/libSvtAv1Enc.dylib', '.'),
    ('/usr/local/lib/libX11-xcb.1.dylib', '.'),
    ('/usr/local/lib/libX11-xcb.dylib', '.'),
    ('/usr/local/lib/libX11.6.dylib', '.'),
    ('/usr/local/lib/libX11.dylib', '.'),
    ('/usr/local/lib/libXau.6.0.0.dylib', '.'),
    ('/usr/local/lib/libXau.6.dylib', '.'),
    ('/usr/local/lib/libXau.dylib', '.'),
    ('/usr/local/lib/libXdmcp.6.dylib', '.'),
    ('/usr/local/lib/libXdmcp.dylib', '.'),
    ('/usr/local/lib/libXext.6.dylib', '.'),
    ('/usr/local/lib/libXext.dylib', '.'),
    ('/usr/local/lib/libXrender.1.dylib', '.'),
    ('/usr/local/lib/libXrender.dylib', '.'),
    ('/usr/local/lib/libaom.3.7.0.dylib', '.'),
    ('/usr/local/lib/libaom.3.dylib', '.'),
    ('/usr/local/lib/libaom.dylib', '.'),
    ('/usr/local/lib/libaribb24.0.dylib', '.'),
    ('/usr/local/lib/libaribb24.dylib', '.'),
    ('/usr/local/lib/libasprintf.0.dylib', '.'),
    ('/usr/local/lib/libasprintf.dylib', '.'),
    ('/usr/local/lib/libass.9.dylib', '.'),
    ('/usr/local/lib/libass.dylib', '.'),
    ('/usr/local/lib/libavcodec.60.3.100.dylib', '.'),
    ('/usr/local/lib/libavcodec.60.dylib', '.'),
    ('/usr/local/lib/libavcodec.dylib', '.'),
    ('/usr/local/lib/libavdevice.60.1.100.dylib', '.'),
    ('/usr/local/lib/libavdevice.60.dylib', '.'),
    ('/usr/local/lib/libavdevice.dylib', '.'),
    ('/usr/local/lib/libavfilter.9.3.100.dylib', '.'),
    ('/usr/local/lib/libavfilter.9.dylib', '.'),
    ('/usr/local/lib/libavfilter.dylib', '.'),
    ('/usr/local/lib/libavformat.60.3.100.dylib', '.'),
    ('/usr/local/lib/libavformat.60.dylib', '.'),
    ('/usr/local/lib/libavformat.dylib', '.'),
    ('/usr/local/lib/libavutil.58.2.100.dylib', '.'),
    ('/usr/local/lib/libavutil.58.dylib', '.'),
    ('/usr/local/lib/libavutil.dylib', '.'),
    ('/usr/local/lib/libb2.1.dylib', '.'),
    ('/usr/local/lib/libb2.dylib', '.'),
    ('/usr/local/lib/libbluray.2.dylib', '.'),
    ('/usr/local/lib/libbluray.dylib', '.'),
    ('/usr/local/lib/libbrotlicommon.1.1.0.dylib', '.'),
    ('/usr/local/lib/libbrotlicommon.1.dylib', '.'),
    ('/usr/local/lib/libbrotlicommon.dylib', '.'),
    ('/usr/local/lib/libbrotlidec.1.1.0.dylib', '.'),
    ('/usr/local/lib/libbrotlidec.1.dylib', '.'),
    ('/usr/local/lib/libbrotlidec.dylib', '.'),
    ('/usr/local/lib/libbrotlienc.1.1.0.dylib', '.'),
    ('/usr/local/lib/libbrotlienc.1.dylib', '.'),
    ('/usr/local/lib/libbrotlienc.dylib', '.'),
    ('/usr/local/lib/libcairo-gobject.2.dylib', '.'),
    ('/usr/local/lib/libcairo-gobject.dylib', '.'),
    ('/usr/local/lib/libcairo-script-interpreter.2.dylib', '.'),
    ('/usr/local/lib/libcairo-script-interpreter.dylib', '.'),
    ('/usr/local/lib/libcairo.2.dylib', '.'),
    ('/usr/local/lib/libcairo.dylib', '.'),
    ('/usr/local/lib/libcjson.1.7.16.dylib', '.'),
    ('/usr/local/lib/libcjson.1.dylib', '.'),
    ('/usr/local/lib/libcjson.dylib', '.'),
    ('/usr/local/lib/libcjson_utils.1.7.16.dylib', '.'),
    ('/usr/local/lib/libcjson_utils.1.dylib', '.'),
    ('/usr/local/lib/libcjson_utils.dylib', '.'),
    ('/usr/local/lib/libcmocka.0.7.0.dylib', '.'),
    ('/usr/local/lib/libcmocka.0.dylib', '.'),
    ('/usr/local/lib/libcmocka.dylib', '.'),
    ('/usr/local/lib/libcrypto.3.dylib', '.'),
    ('/usr/local/lib/libcrypto.dylib', '.'),
    ('/usr/local/lib/libdav1d.6.dylib', '.'),
    ('/usr/local/lib/libdav1d.dylib', '.'),
    ('/usr/local/lib/libevent-2.1.7.dylib', '.'),
    ('/usr/local/lib/libevent.dylib', '.'),
    ('/usr/local/lib/libevent_core-2.1.7.dylib', '.'),
    ('/usr/local/lib/libevent_core.dylib', '.'),
    ('/usr/local/lib/libevent_extra-2.1.7.dylib', '.'),
    ('/usr/local/lib/libevent_extra.dylib', '.'),
    ('/usr/local/lib/libevent_openssl-2.1.7.dylib', '.'),
    ('/usr/local/lib/libevent_openssl.dylib', '.'),
    ('/usr/local/lib/libevent_pthreads-2.1.7.dylib', '.'),
    ('/usr/local/lib/libevent_pthreads.dylib', '.'),
    ('/usr/local/lib/libfontconfig.1.dylib', '.'),
    ('/usr/local/lib/libfontconfig.dylib', '.'),
    ('/usr/local/lib/libfreetype.6.dylib', '.'),
    ('/usr/local/lib/libfreetype.dylib', '.'),
    ('/usr/local/lib/libfribidi.0.dylib', '.'),
    ('/usr/local/lib/libfribidi.dylib', '.'),
    ('/usr/local/lib/libfuse.2.dylib', '.'),
    ('/usr/local/lib/libfuse.dylib', '.'),
    ('/usr/local/lib/libgdbm.6.dylib', '.'),
    ('/usr/local/lib/libgdbm.dylib', '.'),
    ('/usr/local/lib/libgdbm_compat.4.dylib', '.'),
    ('/usr/local/lib/libgdbm_compat.dylib', '.'),
    ('/usr/local/lib/libgettextlib-0.22.2.dylib', '.'),
    ('/usr/local/lib/libgettextlib.dylib', '.'),
    ('/usr/local/lib/libgettextpo.0.dylib', '.'),
    ('/usr/local/lib/libgettextpo.dylib', '.'),
    ('/usr/local/lib/libgettextsrc-0.22.2.dylib', '.'),
    ('/usr/local/lib/libgettextsrc.dylib', '.'),
    ('/usr/local/lib/libgif.7.2.0.dylib', '.'),
    ('/usr/local/lib/libgif.7.dylib', '.'),
    ('/usr/local/lib/libgif.dylib', '.'),
    ('/usr/local/lib/libgio-2.0.0.dylib', '.'),
    ('/usr/local/lib/libgio-2.0.dylib', '.'),
    ('/usr/local/lib/libgit2.1.7.1.dylib', '.'),
    ('/usr/local/lib/libgit2.1.7.dylib', '.'),
    ('/usr/local/lib/libgit2.dylib', '.'),
    ('/usr/local/lib/libglib-2.0.0.dylib', '.'),
    ('/usr/local/lib/libglib-2.0.dylib', '.'),
    ('/usr/local/lib/libgmodule-2.0.0.dylib', '.'),
    ('/usr/local/lib/libgmodule-2.0.dylib', '.'),
    ('/usr/local/lib/libgmp.10.dylib', '.'),
    ('/usr/local/lib/libgmp.dylib', '.'),
    ('/usr/local/lib/libgmpxx.4.dylib', '.'),
    ('/usr/local/lib/libgmpxx.dylib', '.'),
    ('/usr/local/lib/libgnutls-dane.0.dylib', '.'),
    ('/usr/local/lib/libgnutls-dane.dylib', '.'),
    ('/usr/local/lib/libgnutls.30.dylib', '.'),
    ('/usr/local/lib/libgnutls.dylib', '.'),
    ('/usr/local/lib/libgnutlsxx.30.dylib', '.'),
    ('/usr/local/lib/libgnutlsxx.dylib', '.'),
    ('/usr/local/lib/libgobject-2.0.0.dylib', '.'),
    ('/usr/local/lib/libgobject-2.0.dylib', '.'),
    ('/usr/local/lib/libgraphite2.3.2.1.dylib', '.'),
    ('/usr/local/lib/libgraphite2.3.dylib', '.'),
    ('/usr/local/lib/libgraphite2.dylib', '.'),
    ('/usr/local/lib/libgthread-2.0.0.dylib', '.'),
    ('/usr/local/lib/libgthread-2.0.dylib', '.'),
    ('/usr/local/lib/libharfbuzz-cairo.0.dylib', '.'),
    ('/usr/local/lib/libharfbuzz-cairo.dylib', '.'),
    ('/usr/local/lib/libharfbuzz-gobject.0.dylib', '.'),
    ('/usr/local/lib/libharfbuzz-gobject.dylib', '.'),
    ('/usr/local/lib/libharfbuzz-icu.0.dylib', '.'),
    ('/usr/local/lib/libharfbuzz-icu.dylib', '.'),
    ('/usr/local/lib/libharfbuzz-subset.0.dylib', '.'),
    ('/usr/local/lib/libharfbuzz-subset.dylib', '.'),
    ('/usr/local/lib/libharfbuzz.0.dylib', '.'),
    ('/usr/local/lib/libharfbuzz.dylib', '.'),
    ('/usr/local/lib/libhogweed.6.8.dylib', '.'),
    ('/usr/local/lib/libhogweed.6.dylib', '.'),
    ('/usr/local/lib/libhogweed.dylib', '.'),
    ('/usr/local/lib/libhwy.1.0.7.dylib', '.'),
    ('/usr/local/lib/libhwy.1.dylib', '.'),
    ('/usr/local/lib/libhwy.dylib', '.'),
    ('/usr/local/lib/libhwy_contrib.1.0.7.dylib', '.'),
    ('/usr/local/lib/libhwy_contrib.1.dylib', '.'),
    ('/usr/local/lib/libhwy_contrib.dylib', '.'),
    ('/usr/local/lib/libidn2.0.dylib', '.'),
    ('/usr/local/lib/libidn2.dylib', '.'),
    ('/usr/local/lib/libintl.8.dylib', '.'),
    ('/usr/local/lib/libintl.dylib', '.'),
    ('/usr/local/lib/libjpeg.8.3.2.dylib', '.'),
    ('/usr/local/lib/libjpeg.8.dylib', '.'),
    ('/usr/local/lib/libjpeg.dylib', '.'),
    ('/usr/local/lib/libjq.1.dylib', '.'),
    ('/usr/local/lib/libjq.dylib', '.'),
    ('/usr/local/lib/libjxl.0.8.2.dylib', '.'),
    ('/usr/local/lib/libjxl.0.8.dylib', '.'),
    ('/usr/local/lib/libjxl.dylib', '.'),
    ('/usr/local/lib/libjxl_threads.0.8.2.dylib', '.'),
    ('/usr/local/lib/libjxl_threads.0.8.dylib', '.'),
    ('/usr/local/lib/libjxl_threads.dylib', '.'),
    ('/usr/local/lib/liblcms2.2.dylib', '.'),
    ('/usr/local/lib/liblcms2.dylib', '.'),
    ('/usr/local/lib/libleptonica.6.dylib', '.'),
    ('/usr/local/lib/libleptonica.dylib', '.'),
    ('/usr/local/lib/liblua.5.4.6.dylib', '.'),
    ('/usr/local/lib/liblua.5.4.dylib', '.'),
    ('/usr/local/lib/liblua.dylib', '.'),
    ('/usr/local/lib/liblua5.4.dylib', '.'),
    ('/usr/local/lib/liblz4.1.9.4.dylib', '.'),
    ('/usr/local/lib/liblz4.1.dylib', '.'),
    ('/usr/local/lib/liblz4.dylib', '.'),
    ('/usr/local/lib/liblzma.5.dylib', '.'),
    ('/usr/local/lib/liblzma.dylib', '.'),
    ('/usr/local/lib/liblzo2.2.dylib', '.'),
    ('/usr/local/lib/liblzo2.dylib', '.'),
    ('/usr/local/lib/libmbedcrypto.14.dylib', '.'),
    ('/usr/local/lib/libmbedcrypto.3.4.1.dylib', '.'),
    ('/usr/local/lib/libmbedcrypto.dylib', '.'),
    ('/usr/local/lib/libmbedtls.19.dylib', '.'),
    ('/usr/local/lib/libmbedtls.3.4.1.dylib', '.'),
    ('/usr/local/lib/libmbedtls.dylib', '.'),
    ('/usr/local/lib/libmbedx509.3.4.1.dylib', '.'),
    ('/usr/local/lib/libmbedx509.5.dylib', '.'),
    ('/usr/local/lib/libmbedx509.dylib', '.'),
    ('/usr/local/lib/libminizip.1.dylib', '.'),
    ('/usr/local/lib/libminizip.dylib', '.'),
    ('/usr/local/lib/libmp3lame.0.dylib', '.'),
    ('/usr/local/lib/libmp3lame.dylib', '.'),
    ('/usr/local/lib/libmpdec++.2.5.1.dylib', '.'),
    ('/usr/local/lib/libmpdec++.3.dylib', '.'),
    ('/usr/local/lib/libmpdec++.dylib', '.'),
    ('/usr/local/lib/libmpdec.2.5.1.dylib', '.'),
    ('/usr/local/lib/libmpdec.3.dylib', '.'),
    ('/usr/local/lib/libmpdec.dylib', '.'),
    ('/usr/local/lib/libmpg123.0.dylib', '.'),
    ('/usr/local/lib/libmpg123.dylib', '.'),
    ('/usr/local/lib/libnettle.8.8.dylib', '.'),
    ('/usr/local/lib/libnettle.8.dylib', '.'),
    ('/usr/local/lib/libnettle.dylib', '.'),
    ('/usr/local/lib/libnghttp2.14.dylib', '.'),
    ('/usr/local/lib/libnghttp2.dylib', '.'),
    ('/usr/local/lib/libogg.0.dylib', '.'),
    ('/usr/local/lib/libogg.dylib', '.'),
    ('/usr/local/lib/libonig.5.dylib', '.'),
    ('/usr/local/lib/libonig.dylib', '.'),
    ('/usr/local/lib/libopencore-amrnb.0.dylib', '.'),
    ('/usr/local/lib/libopencore-amrnb.dylib', '.'),
    ('/usr/local/lib/libopencore-amrwb.0.dylib', '.'),
    ('/usr/local/lib/libopencore-amrwb.dylib', '.'),
    ('/usr/local/lib/libopenjp2.2.5.0.dylib', '.'),
    ('/usr/local/lib/libopenjp2.7.dylib', '.'),
    ('/usr/local/lib/libopenjp2.dylib', '.'),
    ('/usr/local/lib/libopus.0.dylib', '.'),
    ('/usr/local/lib/libopus.dylib', '.'),
    ('/usr/local/lib/libosxfuse.2.dylib', '.'),
    ('/usr/local/lib/libosxfuse_i64.2.dylib', '.'),
    ('/usr/local/lib/libout123.0.dylib', '.'),
    ('/usr/local/lib/libout123.dylib', '.'),
    ('/usr/local/lib/libp11-kit.0.dylib', '.'),
    ('/usr/local/lib/libp11-kit.dylib', '.'),
    ('/usr/local/lib/libpango-1.0.0.dylib', '.'),
    ('/usr/local/lib/libpango-1.0.dylib', '.'),
    ('/usr/local/lib/libpangocairo-1.0.0.dylib', '.'),
    ('/usr/local/lib/libpangocairo-1.0.dylib', '.'),
    ('/usr/local/lib/libpangoft2-1.0.0.dylib', '.'),
    ('/usr/local/lib/libpangoft2-1.0.dylib', '.'),
    ('/usr/local/lib/libpcre2-16.0.dylib', '.'),
    ('/usr/local/lib/libpcre2-16.dylib', '.'),
    ('/usr/local/lib/libpcre2-32.0.dylib', '.'),
    ('/usr/local/lib/libpcre2-32.dylib', '.'),
    ('/usr/local/lib/libpcre2-8.0.dylib', '.'),
    ('/usr/local/lib/libpcre2-8.dylib', '.'),
    ('/usr/local/lib/libpcre2-posix.3.dylib', '.'),
    ('/usr/local/lib/libpcre2-posix.dylib', '.'),
    ('/usr/local/lib/libpixman-1.0.42.2.dylib', '.'),
    ('/usr/local/lib/libpixman-1.0.dylib', '.'),
    ('/usr/local/lib/libpixman-1.dylib', '.'),
    ('/usr/local/lib/libpng.dylib', '.'),
    ('/usr/local/lib/libpng16.16.dylib', '.'),
    ('/usr/local/lib/libpng16.dylib', '.'),
    ('/usr/local/lib/libportaudio.2.dylib', '.'),
    ('/usr/local/lib/libportaudio.dylib', '.'),
    ('/usr/local/lib/libportaudiocpp.0.dylib', '.'),
    ('/usr/local/lib/libportaudiocpp.dylib', '.'),
    ('/usr/local/lib/libpostproc.57.1.100.dylib', '.'),
    ('/usr/local/lib/libpostproc.57.dylib', '.'),
    ('/usr/local/lib/libpostproc.dylib', '.'),
    ('/usr/local/lib/librav1e.0.6.6.dylib', '.'),
    ('/usr/local/lib/librav1e.0.6.dylib', '.'),
    ('/usr/local/lib/librav1e.dylib', '.'),
    ('/usr/local/lib/librist.4.dylib', '.'),
    ('/usr/local/lib/librist.dylib', '.'),
    ('/usr/local/lib/librubberband.2.dylib', '.'),
    ('/usr/local/lib/librubberband.dylib', '.'),
    ('/usr/local/lib/libsamplerate.0.2.2.dylib', '.'),
    ('/usr/local/lib/libsamplerate.0.dylib', '.'),
    ('/usr/local/lib/libsamplerate.dylib', '.'),
    ('/usr/local/lib/libsharpyuv.0.0.1.dylib', '.'),
    ('/usr/local/lib/libsharpyuv.0.dylib', '.'),
    ('/usr/local/lib/libsharpyuv.dylib', '.'),
    ('/usr/local/lib/libsnappy.1.1.10.dylib', '.'),
    ('/usr/local/lib/libsnappy.1.dylib', '.'),
    ('/usr/local/lib/libsnappy.dylib', '.'),
    ('/usr/local/lib/libsndfile.1.0.37.dylib', '.'),
    ('/usr/local/lib/libsndfile.1.dylib', '.'),
    ('/usr/local/lib/libsndfile.dylib', '.'),
    ('/usr/local/lib/libsodium.23.dylib', '.'),
    ('/usr/local/lib/libsodium.dylib', '.'),
    ('/usr/local/lib/libsoxr-lsr.0.1.9.dylib', '.'),
    ('/usr/local/lib/libsoxr-lsr.0.dylib', '.'),
    ('/usr/local/lib/libsoxr-lsr.dylib', '.'),
    ('/usr/local/lib/libsoxr.0.1.2.dylib', '.'),
    ('/usr/local/lib/libsoxr.0.dylib', '.'),
    ('/usr/local/lib/libsoxr.dylib', '.'),
    ('/usr/local/lib/libspeex.1.dylib', '.'),
    ('/usr/local/lib/libspeex.dylib', '.'),
    ('/usr/local/lib/libsrt.1.5.3.dylib', '.'),
    ('/usr/local/lib/libsrt.1.5.dylib', '.'),
    ('/usr/local/lib/libsrt.dylib', '.'),
    ('/usr/local/lib/libssh2.1.dylib', '.'),
    ('/usr/local/lib/libssh2.dylib', '.'),
    ('/usr/local/lib/libssl.3.dylib', '.'),
    ('/usr/local/lib/libssl.dylib', '.'),
    ('/usr/local/lib/libswresample.4.10.100.dylib', '.'),
    ('/usr/local/lib/libswresample.4.dylib', '.'),
    ('/usr/local/lib/libswresample.dylib', '.'),
    ('/usr/local/lib/libswscale.7.1.100.dylib', '.'),
    ('/usr/local/lib/libswscale.7.dylib', '.'),
    ('/usr/local/lib/libswscale.dylib', '.'),
    ('/usr/local/lib/libsyn123.0.dylib', '.'),
    ('/usr/local/lib/libsyn123.dylib', '.'),
    ('/usr/local/lib/libtasn1.6.dylib', '.'),
    ('/usr/local/lib/libtasn1.dylib', '.'),
    ('/usr/local/lib/libtcl8.6.dylib', '.'),
    ('/usr/local/lib/libtesseract.5.dylib', '.'),
    ('/usr/local/lib/libtesseract.dylib', '.'),
    ('/usr/local/lib/libtextstyle.0.dylib', '.'),
    ('/usr/local/lib/libtextstyle.dylib', '.'),
    ('/usr/local/lib/libtheora.0.dylib', '.'),
    ('/usr/local/lib/libtheora.dylib', '.'),
    ('/usr/local/lib/libtheoradec.1.dylib', '.'),
    ('/usr/local/lib/libtheoradec.dylib', '.'),
    ('/usr/local/lib/libtheoraenc.1.dylib', '.'),
    ('/usr/local/lib/libtheoraenc.dylib', '.'),
    ('/usr/local/lib/libtiff.6.dylib', '.'),
    ('/usr/local/lib/libtiff.dylib', '.'),
    ('/usr/local/lib/libtiffxx.6.dylib', '.'),
    ('/usr/local/lib/libtiffxx.dylib', '.'),
    ('/usr/local/lib/libtk8.6.dylib', '.'),
    ('/usr/local/lib/libturbojpeg.0.3.0.dylib', '.'),
    ('/usr/local/lib/libturbojpeg.0.dylib', '.'),
    ('/usr/local/lib/libturbojpeg.dylib', '.'),
    ('/usr/local/lib/libunbound.8.dylib', '.'),
    ('/usr/local/lib/libunbound.dylib', '.'),
    ('/usr/local/lib/libunibreak.5.dylib', '.'),
    ('/usr/local/lib/libunibreak.dylib', '.'),
    ('/usr/local/lib/libunistring.5.dylib', '.'),
    ('/usr/local/lib/libunistring.dylib', '.'),
    ('/usr/local/lib/libutf8proc.2.dylib', '.'),
    ('/usr/local/lib/libutf8proc.dylib', '.'),
    ('/usr/local/lib/libvidstab.1.2.dylib', '.'),
    ('/usr/local/lib/libvidstab.dylib', '.'),
    ('/usr/local/lib/libvmaf.1.dylib', '.'),
    ('/usr/local/lib/libvmaf.dylib', '.'),
    ('/usr/local/lib/libvorbis.0.dylib', '.'),
    ('/usr/local/lib/libvorbis.dylib', '.'),
    ('/usr/local/lib/libvorbisenc.2.dylib', '.'),
    ('/usr/local/lib/libvorbisenc.dylib', '.'),
    ('/usr/local/lib/libvorbisfile.3.dylib', '.'),
    ('/usr/local/lib/libvorbisfile.dylib', '.'),
    ('/usr/local/lib/libvpx.8.dylib', '.'),
    ('/usr/local/lib/libvpx.dylib', '.'),
    ('/usr/local/lib/libwebp.7.1.8.dylib', '.'),
    ('/usr/local/lib/libwebp.7.dylib', '.'),
    ('/usr/local/lib/libwebp.dylib', '.'),
    ('/usr/local/lib/libwebpdecoder.3.1.8.dylib', '.'),
    ('/usr/local/lib/libwebpdecoder.3.dylib', '.'),
    ('/usr/local/lib/libwebpdecoder.dylib', '.'),
    ('/usr/local/lib/libwebpdemux.2.0.14.dylib', '.'),
    ('/usr/local/lib/libwebpdemux.2.dylib', '.'),
    ('/usr/local/lib/libwebpdemux.dylib', '.'),
    ('/usr/local/lib/libwebpmux.3.0.13.dylib', '.'),
    ('/usr/local/lib/libwebpmux.3.dylib', '.'),
    ('/usr/local/lib/libwebpmux.dylib', '.'),
    ('/usr/local/lib/libx264.164.dylib', '.'),
    ('/usr/local/lib/libx264.dylib', '.'),
    ('/usr/local/lib/libx265.199.dylib', '.'),
    ('/usr/local/lib/libx265.dylib', '.'),
    ('/usr/local/lib/libxcb-composite.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-composite.0.dylib', '.'),
    ('/usr/local/lib/libxcb-composite.dylib', '.'),
    ('/usr/local/lib/libxcb-damage.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-damage.0.dylib', '.'),
    ('/usr/local/lib/libxcb-damage.dylib', '.'),
    ('/usr/local/lib/libxcb-dbe.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-dbe.0.dylib', '.'),
    ('/usr/local/lib/libxcb-dbe.dylib', '.'),
    ('/usr/local/lib/libxcb-dpms.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-dpms.0.dylib', '.'),
    ('/usr/local/lib/libxcb-dpms.dylib', '.'),
    ('/usr/local/lib/libxcb-dri2.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-dri2.0.dylib', '.'),
    ('/usr/local/lib/libxcb-dri2.dylib', '.'),
    ('/usr/local/lib/libxcb-dri3.0.1.0.dylib', '.'),
    ('/usr/local/lib/libxcb-dri3.0.dylib', '.'),
    ('/usr/local/lib/libxcb-dri3.dylib', '.'),
    ('/usr/local/lib/libxcb-ge.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-ge.0.dylib', '.'),
    ('/usr/local/lib/libxcb-ge.dylib', '.'),
    ('/usr/local/lib/libxcb-glx.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-glx.0.dylib', '.'),
    ('/usr/local/lib/libxcb-glx.dylib', '.'),
    ('/usr/local/lib/libxcb-present.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-present.0.dylib', '.'),
    ('/usr/local/lib/libxcb-present.dylib', '.'),
    ('/usr/local/lib/libxcb-randr.0.1.0.dylib', '.'),
    ('/usr/local/lib/libxcb-randr.0.dylib', '.'),
    ('/usr/local/lib/libxcb-randr.dylib', '.'),
    ('/usr/local/lib/libxcb-record.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-record.0.dylib', '.'),
    ('/usr/local/lib/libxcb-record.dylib', '.'),
    ('/usr/local/lib/libxcb-render.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-render.0.dylib', '.'),
    ('/usr/local/lib/libxcb-render.dylib', '.'),
    ('/usr/local/lib/libxcb-res.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-res.0.dylib', '.'),
    ('/usr/local/lib/libxcb-res.dylib', '.'),
    ('/usr/local/lib/libxcb-screensaver.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-screensaver.0.dylib', '.'),
    ('/usr/local/lib/libxcb-screensaver.dylib', '.'),
    ('/usr/local/lib/libxcb-shape.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-shape.0.dylib', '.'),
    ('/usr/local/lib/libxcb-shape.dylib', '.'),
    ('/usr/local/lib/libxcb-shm.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-shm.0.dylib', '.'),
    ('/usr/local/lib/libxcb-shm.dylib', '.'),
    ('/usr/local/lib/libxcb-sync.1.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-sync.1.dylib', '.'),
    ('/usr/local/lib/libxcb-sync.dylib', '.'),
    ('/usr/local/lib/libxcb-xevie.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xevie.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xevie.dylib', '.'),
    ('/usr/local/lib/libxcb-xf86dri.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xf86dri.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xf86dri.dylib', '.'),
    ('/usr/local/lib/libxcb-xfixes.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xfixes.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xfixes.dylib', '.'),
    ('/usr/local/lib/libxcb-xinerama.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xinerama.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xinerama.dylib', '.'),
    ('/usr/local/lib/libxcb-xinput.0.1.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xinput.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xinput.dylib', '.'),
    ('/usr/local/lib/libxcb-xkb.1.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xkb.1.dylib', '.'),
    ('/usr/local/lib/libxcb-xkb.dylib', '.'),
    ('/usr/local/lib/libxcb-xprint.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xprint.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xprint.dylib', '.'),
    ('/usr/local/lib/libxcb-xselinux.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xselinux.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xselinux.dylib', '.'),
    ('/usr/local/lib/libxcb-xtest.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xtest.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xtest.dylib', '.'),
    ('/usr/local/lib/libxcb-xv.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xv.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xv.dylib', '.'),
    ('/usr/local/lib/libxcb-xvmc.0.0.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xvmc.0.dylib', '.'),
    ('/usr/local/lib/libxcb-xvmc.dylib', '.'),
    ('/usr/local/lib/libxcb.1.1.0.dylib', '.'),
    ('/usr/local/lib/libxcb.1.dylib', '.'),
    ('/usr/local/lib/libxcb.dylib', '.'),
    ('/usr/local/lib/libxvidcore.4.dylib', '.'),
    ('/usr/local/lib/libxxhash.0.8.1.dylib', '.'),
    ('/usr/local/lib/libxxhash.0.dylib', '.'),
    ('/usr/local/lib/libxxhash.dylib', '.'),
    ('/usr/local/lib/libyaml-0.2.dylib', '.'),
    ('/usr/local/lib/libyaml.dylib', '.'),
    ('/usr/local/lib/libzimg.2.dylib', '.'),
    ('/usr/local/lib/libzimg.dylib', '.'),
    ('/usr/local/lib/libzmq.5.dylib', '.'),
    ('/usr/local/lib/libzmq.dylib', '.'),
    ('/usr/local/lib/libzstd.1.5.5.dylib', '.'),
    ('/usr/local/lib/libzstd.1.dylib', '.'),
    ('/usr/local/lib/libzstd.dylib', '.'),
    ('/usr/local/lib/p11-kit-proxy.dylib', '.'),
    ('/usr/local/bin/ffprobe','.')],
    datas=datas,
    hiddenimports=['pytorch', 'pkg_resources.py2_warn', 'whisper'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

a.datas += Tree('./model', prefix='model')

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='NocturneAI',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='Punch_Logo.ico'

)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='gui',
)

app = BUNDLE(
    coll,
    name='NocturneAI.app',
    icon=None,
    bundle_identifier="com.hanztech.nocturneai",
    info_plist={
        'NSMicrophoneUsageDescription':'Reason for microphone access',
        'NSPrincipalClass': 'NSApplication',
        'NSAppleScriptEnabled': False,
        "CFBundleDocumentTypes": [
            {
                "CFBundleTypeExtensions": ["pt"],
                "CFBundleTypeName": "[pt]",
                "CFBundleTypeRole": "Editor",
                "CFBundleTypeOSTypes": ["****"],
            }
        ]
    },
)